basket/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete , name='basket_delete'),
    path('update/', views.basket_update , name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('__debug__/', include(debug_toolbar.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
   path('', views.product_all, name='store_home'),
   path('<slug:slug>', views.product_detail, name='product_detail'),
   path('shop/<slug:catagory_slug>/', views.catagory_list, name='catagory_list'),
]

store/models.py
from unicodedata import category
from mptt.models import MPTTModel, TreeForeignKey
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

class Catagory(MPTTModel):
    """
    Category table with mptt
    """

    name = models.CharField(
        verbose_name=_("Category Name"),
        help_text=_("Required and unique"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(verbose_name=_("Category safe url"),max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True,related_name="children")
    is_active = models.BooleanField(default=True)
    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
    def __str__(self):
        return self.name

class ProductType(models.Model):
    name = models.CharField(
        verbose_name=_("product Name"),
        help_text=_("Required and unique"),
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")


    def __str__(self):
        return self.name

class ProductSpecification(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name


class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Catagory, on_delete=models.RESTRICT)
    title = models.CharField(verbose_name=_("title"), help_text=_("Required"), max_length=255)
    description = models.CharField(max_length=255, verbose_name=_("description"), help_text=_("Not Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(verbose_name=_('Regular price'), help_text=_("maximum 999.99"), 
    error_messages={
        "name": {
            "max_length": _("the price must be between 0 and 999.99"),
        },
    },
    max_digits=5,
    decimal_places=2,)

    regular_price = models.DecimalField(verbose_name=_('Discount price'), help_text = _("maximum 999.99"), error_messages = {
        "name": {
            "max_length": _("the price must be between 0 and 999.99"),
        },
    },
    max_digits = 5,
    decimal_places = 2,)
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

class ProductSpecificationValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value

class ProductImage(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        max_length=255,
        null=True,
        blank=True, 
    )
    alt_text = models.CharField(
        verbose_name=_("altenative text"),
        help_text=_("please add product text"),
        max_length=255,
        null=True,
        blank=True, 
    )

    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Catagory, Product


def product_all(request):
    products = Product.objects.prefetch_related("product_image").filter(is_active=True)
    return render(request, 'store/index.html', {'products': products}) 

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, is_active=True)
    return render(request, 'store/single.html', {'product': product})

def catagory_list(request, catagory_slug):
    catagory = get_object_or_404(Catagory, slug=catagory_slug)
    products = Product.objects.filter(catagory__in=Catagory.objects.get(name=catagory_slug).get_decendants(include_self=True))
    return render(request, 'store/catagory.html', {'catagory': catagory, 'products': products})

templates/store/catagory.html
{% extends "base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="container">
    <div class="row">
      <div class="album">


        <div class="pb-3"><h1 class="h3">Popular</h1></div>
        {% if  not products %}
        <div class="col-12">There are currently no products actives</div>
        {% else %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

          {% for product in products %}

          <div class="col">
            <div class="card border-0">
              {% for image in product.product_image.all %}
            
              {% if image.is_feature %}
              <img class="img-fluid" alt="{{ image.image.alt_text }}" src="{{ image.image.url }}" >
   
              {% endif %}
                
            {% endfor %}              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">£{{product.regular_price}}</small>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
    
      {% endif %}
        
      </div>
    </div>

  </div>


</main>

{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% block title %}Store - low prices in books and more{% endblock %}
{% block content %}



<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
        etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-3">Make an account</a>
      </p>
    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="pb-3 h5">All Books</div>
    {% if  not products %}
    <div class="col-12">There are currently no products actives</div>
    {% else %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
      {% for product in products %}

      <div class="col">
        <div class="card shadow-sm">
          
          
          <div class="card-body">
            {% for image in product.product_image.all %}
            
            {% if image.is_feature %}
            <img class="img-fluid" alt="{{ image.image.alt_text }}" src="{{ image.image.url }}" >
 
            {% endif %}
              
          {% endfor %}
            <p class="card-text">
              <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted">9min read</small>
            </div>
          </div>
        </div>
      </div>

      {% endfor %}



    </div>
    {% endif %}
  </div>
</div>


{% endblock %}

templates/store/single.html
{% extends "base.html" %}
{% load static %}
{%block stylesheet%}{% static 'store/css/store.css' %} {% endblock %}
{% if product %}{{ product.name }}{% else %}Products{% endif %}

{% block content %}

<main class="pt-2">

    <div class="container" style="max-width: 1000px">

        <div class="row g-3">

            <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
                <div class="d-grid gap-2">
                    <div class="d-flex d-flex-inline justify-content-between">
                        <div><span class="h3">£{{ product.regular_price }}</span>
                            <p class="text-muted">includes tax</p>
                        </div>
                        <div>
                            <label for="select">Qty</label>
                            <select id="select" class="h6 store-select-dropdown" >
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                    </div>
                    <hr>
                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
                        basket</button>
                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-light fw500">Add to
                        Favorites</button>
                </div>
            </div>

            <div class="col-md-7 col-lg-7 p-0">
                <div class="card mb-3 border-0">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-body p-1">
                                <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                                <div class="bg-light">
                                    
                                    {% for image in product.product_image.all %}
                                        {% if image.is_feature %}
                                        <img class="img-fluid mx-auto d-block" width="200px"

                                        alt="{{ image.image.alt_text }}" src="{{ image.image.url }}"> </div>
            

                                        {% endif %}
                                    {% endfor %}
                                        
                                    
                            </div>

                        </div>
                    </div>
                </div>
                
            </div>

        </div>
    </div>
</main>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}